// packages/sard-uniapp/src/calendar/calendar.vue
<template>
  <view :class="calendarClass" :style="calendarStyle">
    <view :class="bem.e('header')">
      <view v-if="!severalMonths" :class="bem.e('toolbar')">
        <view :class="bem.e('toolbar-inner')">
          <Button
            type="pale-text"
            theme="body"
            :disabled="
              toMonthNumber(innerCurrentDate) <= toMonthNumber(minDate)
            "
            @click="onPrevMonthClick"
          >
            <Icon name="left" size="32rpx" />
          </Button>
          <Button type="pale-text" theme="body" @click="onMonthClick">
            {{
              t('monthTitle', {
                year: innerCurrentDate.getFullYear(),
                month: String(innerCurrentDate.getMonth() + 1).padStart(2, '0'),
              })
            }}
          </Button>
          <Button
            type="pale-text"
            theme="body"
            :disabled="
              toMonthNumber(innerCurrentDate) >= toMonthNumber(maxDate)
            "
            @click="onNextMonthClick"
          >
            <Icon name="right" size="32rpx" />
          </Button>
        </view>
      </view>
      <view :class="bem.e('week')">
        <view v-for="(item, i) in weeks" :key="i" :class="bem.e('week-item')">
          {{ t(`weeks.${item}`) }}
        </view>
      </view>
    </view>
    <scroll-view :scroll-y="severalMonths" :class="bem.e('body')">
      <Month
        v-for="(month, i) in months"
        :key="i"
        :year="month[0]"
        :month="month[1]"
        :type="type"
        :min-date="minDate"
        :max-date="maxDate"
        :current-dates="currentDates"
        :formatter="formatter"
        :disabled-date="disabledDate"
        :today-number="todayNumber"
        :week-starts-on="weekStartsOn"
        :several-months="severalMonths"
        :t="t"
        :bem="bem"
        @day-click="handleDayClick"
      />
    </scroll-view>
  </view>

  <Popout
    v-if="!severalMonths"
    v-model:visible="pickerVisible"
    type="compact"
    @confirm="onPickerConfirm"
  >
    <DatetimePicker
      type="yM"
      v-model="pickerValue"
      :min="minDate"
      :max="maxDate"
    />
  </Popout>
</template>

<script lang="ts">
export default {
  options: {
    virtualHost: true,
    styleIsolation: 'shared',
  },
}
</script>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import {
  classNames,
  stringifyStyle,
  createBem,
  minmaxDate,
  toDateNumber,
  toMonthNumber,
  getPrevMonthDate,
  getNextMonthDate,
} from '../utils'
import {
  calendarProps,
  getMaxDate,
  getMinDate,
  sortDates,
  weeksIndex,
} from './common'
import Button from '../button/button.vue'
import Icon from '../icon/icon.vue'
import { useTranslate } from '../locale'
import Month from './month.vue'
import Popout from '../popout/popout.vue'
import DatetimePicker from '../datetime-picker/datetime-picker.vue'

const props = defineProps(calendarProps)

const emit = defineEmits(['update:model-value'])

const bem = createBem('calendar')

// main
const { t } = useTranslate('calendar')

const minDate = computed(() => {
  return props.min || getMinDate(props.severalMonths)
})

const maxDate = computed(() => {
  const maxDate = props.max || getMaxDate(props.severalMonths)
  return maxDate.getTime() < minDate.value.getTime()
    ? new Date(minDate.value)
    : maxDate
})

const innerValue = ref<Date | Date[] | undefined>(
  props.modelValue ?? (props.type === 'single' ? undefined : []),
)

watch(
  () => props.modelValue,
  () => {
    if (innerValue.value !== props.modelValue) {
      innerValue.value =
        props.modelValue ?? (props.type === 'single' ? undefined : [])
    }
  },
)

const innerCurrentDate = ref(
  minmaxDate(props.currentDate || new Date(), minDate.value, maxDate.value),
)

watch(
  () => props.currentDate,
  () => {
    innerCurrentDate.value = minmaxDate(
      props.currentDate || new Date(),
      minDate.value,
      maxDate.value,
    )
  },
)

watch(innerValue, () => {
  const onlyOneDate = Array.isArray(innerValue.value)
    ? innerValue.value.length === 1
      ? innerValue.value[0]
      : undefined
    : innerValue.value
  if (
    onlyOneDate &&
    toMonthNumber(onlyOneDate) !== toMonthNumber(innerCurrentDate.value)
  ) {
    innerCurrentDate.value = onlyOneDate
  }
})

const startDate = ref(
  props.type === 'range' &&
    Array.isArray(innerValue.value) &&
    innerValue.value.length === 1
    ? innerValue.value[0]
    : undefined,
)

// toolbar
const onPrevMonthClick = () => {
  innerCurrentDate.value = getPrevMonthDate(innerCurrentDate.value)
}

const onNextMonthClick = () => {
  innerCurrentDate.value = getNextMonthDate(innerCurrentDate.value)
}

// month picker
const pickerVisible = ref(false)
const pickerValue = ref(innerCurrentDate.value)

const onMonthClick = () => {
  pickerValue.value = innerCurrentDate.value
  pickerVisible.value = true
}

const onPickerConfirm = () => {
  if (
    toMonthNumber(innerCurrentDate.value) !== toMonthNumber(pickerValue.value)
  ) {
    innerCurrentDate.value = pickerValue.value
  }
}

// weeks
const weeks = computed(() => {
  return weeksIndex
    .slice(props.weekStartsOn)
    .concat(weeksIndex.slice(0, props.weekStartsOn))
})

// month
const months = computed(() => {
  if (!props.severalMonths) {
    return [
      [innerCurrentDate.value.getFullYear(), innerCurrentDate.value.getMonth()],
    ]
  }
  const minYear = minDate.value.getFullYear()
  const minMonth = minDate.value.getMonth()
  const maxYear = maxDate.value.getFullYear()
  const maxMonth = maxDate.value.getMonth()

  const months = (maxYear - minYear) * 12 + (maxMonth - minMonth)

  return Array(months)
    .fill(0)
    .map((_, i) => {
      return [minYear + Math.floor((minMonth + i) / 12), (minMonth + i) % 12]
    })
})

// day
const todayNumber = toDateNumber(new Date())

const currentDates = computed(() => {
  let dates: Date[]

  if (props.type === 'range' && startDate.value) {
    dates = [startDate.value]
  } else {
    if (Array.isArray(innerValue.value)) {
      dates = innerValue.value
    } else if (innerValue.value) {
      dates = [innerValue.value]
    } else {
      dates = []
    }
  }

  return dates
})

const handleDayClick = (date: Date) => {
  let nextValue: Date | Date[] | undefined

  if (props.type === 'single') {
    nextValue = date
  } else if (props.type === 'multiple') {
    if (Array.isArray(innerValue.value)) {
      if (
        innerValue.value.some((d) => toDateNumber(d) === toDateNumber(date))
      ) {
        nextValue = innerValue.value.filter(
          (d) => toDateNumber(d) !== toDateNumber(date),
        )
      } else {
        if (innerValue.value.length >= props.maxDays) {
          props.overMaxDays?.()
          return
        }
        nextValue = sortDates(innerValue.value.concat(date))
      }
    }
  } else if (props.type === 'range') {
    if (startDate.value) {
      const startDays = toDateNumber(startDate.value)
      const endDays = toDateNumber(date)

      if (!props.allowSameDay && startDays === endDays) {
        return
      }

      const startAgain = endDays < startDays
      if (startAgain) {
        startDate.value = date
        return
      }

      let endDate = date

      if (endDays - startDays + 1 > props.maxDays) {
        props.overMaxDays?.()

        endDate = new Date(startDate.value)
        endDate.setDate(endDate.getDate() + (props.maxDays - 1))
      }

      nextValue = [startDate.value, endDate]
    } else {
      nextValue = []
    }

    startDate.value = startDate.value ? undefined : date
  }

  if (nextValue !== undefined) {
    innerValue.value = nextValue
    emit('update:model-value', nextValue)
  }
}

// others
const calendarClass = computed(() => {
  return classNames(
    bem.b(),
    bem.m('several', props.severalMonths),
    props.rootClass,
  )
})

const calendarStyle = computed(() => {
  return stringifyStyle(props.rootStyle)
})
</script>

<style lang="scss">
@use './index.scss';
</style>

// packages/sard-uniapp/components/calendar/index.tsx
import {
  CSSProperties,
  forwardRef,
  ReactNode,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react'
import classNames from 'classnames'
import { useControllableValue, useEvent, useResizeObserver } from '../../use'
import { getDaysInMonth, getWeekOnFirstDay, toDateNumber } from '../../utils'
import { scrollIntoView, ScrollIntoViewPosition } from '../../utils/dom'
import useTranslate from '../locale/useTranslate'

export interface CalendarDay {
  date: Date
  topInfo: ReactNode
  text: ReactNode
  bottomInfo: ReactNode
  type: 'same' | 'start' | 'middle' | 'end' | 'disabled' | 'selected' | 'normal'
  className?: string
  style?: CSSProperties
}

interface CalendarBaseProps {
  className?: string
  style?: CSSProperties
  children?: ReactNode
  min?: Date
  max?: Date
  title?: ReactNode
  disabledDate?: (date: Date) => boolean
  maxDays?: number
  overMaxDays?: () => void
  weekStartsOn?: number
  formatter?: (day: CalendarDay) => void
  allowSameDay?: boolean
}

export interface CalendarSingleProps extends CalendarBaseProps {
  type?: 'single'
  value?: Date
  defaultValue?: Date
  onChange?: (value: Date) => void
}

export interface CalendarMultipleProps extends CalendarBaseProps {
  type?: 'multiple'
  value?: Date[]
  defaultValue?: Date[]
  onChange?: (value: Date[]) => void
}

export interface CalendarRangeProps extends CalendarBaseProps {
  type?: 'range'
  value?: Date[]
  defaultValue?: Date[]
  onChange?: (value: Date[]) => void
}

export type CalendarProps =
  | CalendarSingleProps
  | CalendarMultipleProps
  | CalendarRangeProps

const weeks = [0, 1, 2, 3, 4, 5, 6]

const getWeeks = (weekStartsOn: number) => {
  return weeks.slice(weekStartsOn).concat(weeks.slice(0, weekStartsOn))
}

const getOffsetWeek = (week: number, weekStartsOn: number) => {
  return (week - weekStartsOn + 7) % 7
}

const getMinDate = () => {
  return new Date()
}

const getMaxDate = () => {
  const date = new Date()
  date.setMonth(date.getMonth() + 6)
  return date
}

const sortDates = (dates: Date[]) => {
  return dates.sort((a, b) => a.getTime() - b.getTime())
}

export interface CalendarRef {
  scrollToDate: (
    date: Date,
    align: 'start' | 'center' | 'end' | 'nearest',
  ) => void
}

export const Calendar = forwardRef<CalendarRef, CalendarProps>((props, ref) => {
  const [t] = useTranslate('calendar')

  const {
    className,
    style,
    children,
    min,
    max,
    title,
    disabledDate,
    type = 'single',
    value,
    defaultValue,
    onChange,
    maxDays = Number.MAX_SAFE_INTEGER,
    overMaxDays,
    weekStartsOn = 0,
    formatter,
    allowSameDay,
    ...restProps
  } = props

  const dateElements = useRef<Record<string, HTMLElement>>({})

  const minDate = useMemo(() => {
    return min || getMinDate()
  }, [min])

  const maxDate = useMemo(() => {
    const maxDate = max || getMaxDate()
    return maxDate.getTime() < minDate.getTime() ? new Date(minDate) : maxDate
  }, [max])

  const minMonthCount = useMemo(() => {
    return minDate.getFullYear() * 12 + minDate.getMonth() + 1
  }, [min])

  const maxMonthCount = useMemo(() => {
    return maxDate.getFullYear() * 12 + maxDate.getMonth() + 1
  }, [max])

  const getYearMonthByIndex = (index: number): [number, number] => {
    const monthCount = minMonthCount + index
    return [Math.ceil(monthCount / 12 - 1), monthCount % 12 || 12]
  }

  const [innerValue, setInnerValue] = useControllableValue<Date | Date[]>(
    props,
    {
      initialValue: () => (type === 'single' ? null : []),
    },
  )

  const [startDate, setStartDate] = useState<Date>(() => {
    return type === 'range' &&
      Array.isArray(innerValue) &&
      innerValue.length === 1
      ? innerValue[0]
      : null
  })

  const todayDays = useMemo(() => toDateNumber(new Date()), [])

  const handleDayClick = (date: Date, disabled: boolean) => {
    if (disabled) {
      return
    }

    let val: Date | Date[]

    if (type === 'single') {
      val = date
    } else if (type === 'multiple') {
      if (Array.isArray(innerValue)) {
        if (innerValue.some((d) => toDateNumber(d) === toDateNumber(date))) {
          val = innerValue.filter((d) => toDateNumber(d) !== toDateNumber(date))
        } else {
          if (innerValue.length >= maxDays) {
            overMaxDays?.()
            return
          }
          val = sortDates(innerValue.concat(date))
        }
      }
    } else if (type === 'range') {
      if (startDate) {
        const startDays = toDateNumber(startDate)
        const endDays = toDateNumber(date)

        if (!allowSameDay && startDays === endDays) {
          return
        }

        const startAgain = endDays < startDays
        if (startAgain) {
          setStartDate(date)
          return
        }

        let endDate = date

        if (endDays - startDays + 1 > maxDays) {
          overMaxDays?.()

          endDate = new Date(startDate)
          endDate.setDate(endDate.getDate() + (maxDays - 1))
        }

        val = [startDate, endDate]
      } else {
        val = []
      }

      setStartDate(startDate ? null : date)
    }

    setInnerValue(val)
  }

  const scrollToDate = useEvent(
    (date: Date, align: ScrollIntoViewPosition = 'nearest') => {
      const el = dateElements.current[toDateNumber(date)] as HTMLElement

      if (el) {
        scrollIntoView(el, {
          block: align,
        })
      }
    },
  )

  // 滚动定位到选中日期的节点
  const [ResizeSpy] = useResizeObserver(() => {
    const date = type === 'single' ? innerValue : innerValue[0] || startDate
    if (date) {
      scrollToDate(date)
    }
  })

  useImperativeHandle(ref, () => ({
    scrollToDate,
  }))

  const renderMonth = (
    currentDates: Date[],
    [year, month]: [number, number],
  ) => {
    const days = getDaysInMonth(year, month)
    let nextDate: Date | undefined
    let nextSelected: boolean | undefined

    return (
      <div key={year * 100 + month} className="s-calendar-month">
        <div className="s-calendar-month-title">
          {t('monthTitle')(year, month)}
        </div>
        <div className="s-calendar-month-body">
          {Array(days)
            .fill(0)
            .map((_, i) => {
              const date = nextDate ?? new Date(year, month - 1, i + 1)
              const dateDays = toDateNumber(date)
              const selected =
                nextSelected ??
                currentDates.some((d) => toDateNumber(d) === dateDays)

              if (i < days - 1) {
                nextDate = new Date(year, month - 1, i + 2)
                nextSelected = currentDates.some(
                  (d) => toDateNumber(d) === toDateNumber(nextDate),
                )
              } else {
                nextDate = nextSelected = undefined
              }

              let disabled = false

              if (disabledDate) {
                disabled = disabledDate(date)
              }

              if (
                dateDays < toDateNumber(minDate) ||
                dateDays > toDateNumber(maxDate)
              ) {
                disabled = true
              }

              const isStart =
                type === 'range' &&
                currentDates[0] &&
                toDateNumber(currentDates[0]) === dateDays

              const isMiddle =
                type === 'range' &&
                currentDates.length === 2 &&
                dateDays > toDateNumber(currentDates[0]) &&
                dateDays < toDateNumber(currentDates[1])

              const isEnd =
                type === 'range' &&
                currentDates[1] &&
                toDateNumber(currentDates[1]) === dateDays

              const day: CalendarDay = {
                date,
                topInfo: '',
                text: i + 1,
                bottomInfo: '',
                type:
                  isStart && isEnd
                    ? 'same'
                    : isStart
                    ? 'start'
                    : isMiddle
                    ? 'middle'
                    : isEnd
                    ? 'end'
                    : disabled
                    ? 'disabled'
                    : selected
                    ? 'selected'
                    : 'normal',
              }

              formatter?.(day)

              return (
                <div
                  key={year * 10000 + month * 100 + i}
                  ref={(el) => (dateElements.current[dateDays] = el)}
                  className={classNames(
                    's-calendar-day',
                    {
                      's-calendar-day-selected': selected,
                      's-calendar-day-next-selected': selected && nextSelected,
                      's-calendar-day-start': isStart,
                      's-calendar-day-end': isEnd,
                      's-calendar-day-middle': isMiddle,
                      's-calendar-day-disabled': disabled,
                      's-calendar-day-today': todayDays === dateDays,
                    },
                    day.className,
                  )}
                  style={{
                    gridColumnStart:
                      i === 0
                        ? getOffsetWeek(
                            getWeekOnFirstDay(year, month),
                            weekStartsOn,
                          ) + 1
                        : '',
                    ...day.style,
                  }}
                  onClick={() => handleDayClick(date, disabled)}
                >
                  {day.topInfo && (
                    <div className="s-calendar-topinfo">{day.topInfo}</div>
                  )}
                  {day.text}
                  {day.bottomInfo && (
                    <div className="s-calendar-bottominfo">
                      {day.bottomInfo}
                    </div>
                  )}
                </div>
              )
            })}
          <div className="s-calendar-mark">{month}</div>
        </div>
      </div>
    )
  }

  const currentDates = useMemo(() => {
    let dates: Date[]

    if (type === 'range' && startDate) {
      dates = [startDate]
    } else {
      if (Array.isArray(innerValue)) {
        dates = innerValue
      } else if (innerValue) {
        dates = [innerValue]
      } else {
        dates = []
      }
    }

    return dates
  }, [innerValue, startDate, type])

  return (
    <div {...restProps} className={classNames('s-calendar', className)}>
      <ResizeSpy />
      <div className="s-calendar-header">
        {title && <div className="s-calendar-title">{title}</div>}
        <div className="s-calendar-week">
          {getWeeks(weekStartsOn).map((item) => (
            <div key={item} className="s-calendar-week-item">
              {t('weeks')[item]}
            </div>
          ))}
        </div>
      </div>
      <div className="s-calendar-body">
        {Array(maxMonthCount - minMonthCount + 1)
          .fill(0)
          .map((_, i) => renderMonth(currentDates, getYearMonthByIndex(i)))}
      </div>
      <div className="s-calendar-footer"></div>
    </div>
  )
})

export default Calendar
